# ===============================
# POSTGRESQL LOCAL DATABASE
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/Mylogin
spring.datasource.username=postgres
spring.datasource.password=Srihari@123

spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#-------------------- this is a email service
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kosurusrihari5@gmail.com
spring.mail.password=txzirttqzncqwjux
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
